version: "3.7"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "digital_bank"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      UPLOAD_LIMIT: 300M
    ports:
      - "8888:80"
    depends_on:
      - mysql
  api-test:
    container_name: challenge-golang-api-test
    build: 
      context: ./challenge-golang-stone
      dockerfile: ./Dockerfile.test
    depends_on:
      - "mysql"
    ports:
      - "5000:5000"
    volumes:
      - ./challenge-golang-stone:/go/src/app
